source "https://rubygems.org"

gem "rails", "4.2.0"
gem "mysql2"
gem "bootstrap-sass",       "3.2.0.0"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "devise"
gem "fullcalendar-rails"
gem "momentjs-rails"
gem "select2-rails"
gem "jquery-turbolinks"
gem "websocket-rails"
gem "cancancan", "~> 1.10.1"
gem "kendoui-rails", "~> 0.1.1"
gem "redis-rails"
gem "sidekiq", "~> 3.3.4"
gem "rails_config"
gem "ransack"
gem "carrierwave"
gem "mini_magick"
gem "deep_cloneable", "~> 2.1.1"
gem "kaminari"
gem "kaminari-bootstrap"

group :development, :test do
  gem "faker", "1.4.2"
  gem "factory_girl_rails"
  gem "letter_opener"
  gem "byebug"
  gem "web-console", "~> 2.0"
  gem "rspec-rails", "~> 3.0"
end
